Repository sadainiqrar/emumba-streaming-app, pull requests merged in 2025-01, with the labels that each got.

#5 RTMP Live stream
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/record.html
  public/watch.html
  public/watch2.html
  src/app/app.module.ts
  src/mediaServer/mediaServer.module.ts
  src/mediaServer/mediaServer.service.ts
  src/stream/liveStream.processor.ts
  src/stream/stream.gateway.ts
  src/stream/stream.module.ts
  src/stream/stream.service.ts
Labels: suggest-reviewer, missing-jira, 30 min review

#6 feature/websocket-auth
  package-lock.json
  package.json
  src/chat/chat.gateway.ts
  src/common/middleware/websocket-auth.middleware.ts
  src/stream/stream.gateway.ts
  src/utils/Guards.ts
Labels: missing-jira, 5 min review

#8 [chore/stream-code-refactor]: add endpoint to retrieve streams by status
  src/stream/stream.controller.ts
  src/stream/stream.service.ts
Labels: 1 min review, missing-jira
